[package]
name = "multitor-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
default-run = "EvertyDisplay"

[[bin]]
name = "EvertyDisplay"
path = "src/main.rs"

[dependencies]
multitor-ipc = { path = "../ipc" }
multitor-driver-manager = { path = "../driver-manager" }
iced = { version = "0.14", features = ["tokio", "canvas", "svg", "image"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
windows = { workspace = true }

[build-dependencies]
winres = "0.1"
